title: Part Time Programming
author: jmullin1234
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  a blog about all of the challenges of finding your way in computer science, while working in an unrelated field and supporting a growing family

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
